campaigns/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView, logout_then_login


app_name = "campaigns"

urlpatterns = [

    url(r'^list/$', views.CampaignListView.as_view(), name='list'),
    url(r'^detail/(?P<slug>[-\w]+)/$', views.CampaignDetailView.as_view(), name="detail"),
    url(r'^prospect/get/(?P<slug>[-\w]+)/$', views.prospect_get, name="prospect_get"),


    # url('(?P<slug>[-\w]+)/(?P<pk>\d+)/$', views.posts, name='posts'),

    # path('campaign/detail/<slug:slug>/', views.CampaignDetailView.as_view(), name='detail'),

]

fls_crm/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('portal.urls', namespace='portal')),
    url(r'crm_admin/', include('crm_admin.urls', namespace='crm_admin')),
    url(r'prospects/', include('prospects.urls', namespace='prospects')),
    url(r'campaigns/', include('campaigns.urls', namespace='campaigns')),
    url(r'results/', include('results.urls', namespace='results')),

]

portal/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView, logout_then_login

app_name = "portal"

urlpatterns = [
    url(r'^login/$', LoginView.as_view(template_name='portal/login.html'), name='login'),
    url(r'^logout/$', logout_then_login, name='logout'),
    url(r'^$', views.HomeView.as_view(), name='home'),

    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),

]

portal/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
import datetime
from django.db.models.signals import post_save
from django.contrib.auth.models import User as Django_User_Model

User_Model = Django_User_Model
#
# class User(Django_User_Model):
#
#     class Meta:
#         proxy = True
#         # ordering = ('first_name', )
#
#     def get_display_text(self):
#         return self.executive.first_name


def create_executive(instance, sender, *args, **kwargs):
    if not hasattr(instance, 'executive'):
        Executive.objects.create(user=instance)


post_save.connect(create_executive, sender=Django_User_Model)


class Executive(models.Model):
    user = models.OneToOneField(User_Model, on_delete=models.PROTECT)

    first_name = models.CharField(max_length=32, blank=True)
    last_name = models.CharField(max_length=32, blank=True)

    employee_id = models.CharField(max_length=12, blank=True)

    date_of_birth = models.DateField(blank=True, null=True)
    details = models.TextField(blank=True)

    def __str__(self):
        return self.user.__str__()

    @property
    def get_display_text(self):
        if self.first_name:
            return self.first_name
        else:
            return self.user.username

    @property
    def get_full_name(self):
        return "{} {}".format(self.first_name, self.last_name)

    @property
    def get_employee_id(self):
        if self.employee_id:
            return self.employee_id
        else:
            return "Not entered yet"

    @property
    def get_age(self):
        return datetime.date.today() - self.date_of_birth

portal/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic import View, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Executive


class HomeView(LoginRequiredMixin, View):

    # def get(self, request):
    #     if request.user.is_superuser:
    #         return redirect('crm_admin:home')
    #     else:
    #         return render(request, 'portal/home.html')
    def get(self, request):
        return render(request, 'portal/home.html')


class ProfileView(LoginRequiredMixin, DetailView):

    template_name = "portal/profile.html"
    context_object_name = "executive"

    def get_object(self, queryset=None):
        return self.request.user.executive


#
# e
# @login_required
# def profile(request):
#
#     context = {"executive": }
#
#     return render(rquest, 'portal/profile.html', context)
#

portal/templates/portal/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="en">

<head>

    {% block full_title %}
        <title>{% block title %}base file{% endblock %} - Fine-Leap Systems</title>
    {% endblock %}

    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- favicon
		============================================ -->



    <link rel="shortcut icon" type="image/x-icon" href="{% static "img/logo/favicon.png" %}">
    <!-- Google Fonts
		============================================ -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,900" rel="stylesheet">
    <!-- Bootstrap CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <!-- Bootstrap CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}">
    <!-- owl.carousel CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/owl.carousel.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.theme.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.transitions.css" %}">
    <!-- animate CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/animate.css" %}">
    <!-- normalize CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/normalize.css" %}">
    <!-- meanmenu icon CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/meanmenu.min.css" %}">
    <!-- main CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/main.css" %}">
    <!-- educate icon CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/educate-custon-icon.css" %}">
    <!-- morrisjs CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/morrisjs/morris.css" %}">
    <!-- mCustomScrollbar CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/scrollbar/jquery.mCustomScrollbar.min.css" %}">
    <!-- metisMenu CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/metisMenu/metisMenu.min.css" %}">
    <link rel="stylesheet" href="{% static "css/metisMenu/metisMenu-vertical.css" %}">
    <!-- calendar CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/calendar/fullcalendar.min.css" %}">
    <link rel="stylesheet" href="{% static "css/calendar/fullcalendar.print.min.css" %}">
    <!-- style CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <!-- responsive CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/responsive.css" %}">

    <link rel="stylesheet" type="text/css" href="{% static "css/crm_custom.css" %}">

    <!-- modernizr JS
		============================================ -->
    <script src="{% static "js/vendor/modernizr-2.8.3.min.js" %}"></script>



</head>

<body>

    <!-- Start Left menu area -->
    {% include "portal/left_menu.html" %}
    <!-- End Left menu area -->

    <!-- Start Welcome area -->
    <div class="all-content-wrapper">


        <!-- Start Header -->
        {% include "portal/header.html" %}
        <!-- End Header -->

        {% block content %}
        {% endblock %}

        <!-- Start Footer -->
        {% include "portal/footer.html" %}
        <!-- End Footer -->

    </div>


    <!-- Start Scripts -->

    <!-- jquery
		============================================ -->
    <script src="{% static "js/vendor/jquery-1.12.4.min.js" %}"></script>
    <!-- bootstrap JS
		============================================ -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <!-- wow JS
		============================================ -->
    <script src="{% static "js/wow.min.js" %}"></script>
    <!-- price-slider JS
		============================================ -->
    <script src="{% static "js/jquery-price-slider.js" %}"></script>
    <!-- meanmenu JS
		============================================ -->
    <script src="{% static "js/jquery.meanmenu.js" %}"></script>
    <!-- owl.carousel JS
		============================================ -->
    <script src="{% static "js/owl.carousel.min.js" %}"></script>
    <!-- sticky JS
		============================================ -->
    <script src="{% static "js/jquery.sticky.js" %}"></script>
    <!-- scrollUp JS
		============================================ -->
    <script src="{% static "js/jquery.scrollUp.min.js" %}"></script>
    <!-- counterup JS
		============================================ -->
    <script src="{% static "js/counterup/jquery.counterup.min.js" %}"></script>
    <script src="{% static "js/counterup/waypoints.min.js" %}"></script>
    <script src="{% static "js/counterup/counterup-active.js" %}"></script>
    <!-- mCustomScrollbar JS
		============================================ -->
    <script src="{% static "js/scrollbar/jquery.mCustomScrollbar.concat.min.js" %}"></script>
    <script src="{% static "js/scrollbar/mCustomScrollbar-active.js" %}"></script>
    <!-- metisMenu JS
		============================================ -->
    <script src="{% static "js/metisMenu/metisMenu.min.js" %}"></script>
    <script src="{% static "js/metisMenu/metisMenu-active.js" %}"></script>
    <!-- morrisjs JS
		============================================ -->
    <script src="{% static "js/morrisjs/raphael-min.js" %}"></script>
    <script src="{% static "js/morrisjs/morris.js" %}"></script>
    <script src="{% static "js/morrisjs/morris-active.js" %}"></script>
    <!-- morrisjs JS
		============================================ -->
    <script src="{% static "js/sparkline/jquery.sparkline.min.js" %}"></script>
    <script src="{% static "js/sparkline/jquery.charts-sparkline.js" %}"></script>
    <script src="{% static "js/sparkline/sparkline-active.js" %}"></script>
    <!-- calendar JS
		============================================ -->
    <script src="{% static "js/calendar/moment.min.js" %}"></script>
    <script src="{% static "js/calendar/fullcalendar.min.js" %}"></script>
    <script src="{% static "js/calendar/fullcalendar-active.js" %}"></script>
    <!-- plugins JS
		============================================ -->
    <script src="{% static "js/plugins.js" %}"></script>
    <!-- main JS
		============================================ -->
    <script src="{% static "js/main.js" %}"></script>
    <!-- tawk chat JS
		============================================ -->
    <script src="{% static "js/tawk-chat.js" %}"></script>

    <!-- End Scripts -->


</body>

</html>

portal/templates/portal/footer.html
    {% load static %}
    <div class="footer-copyright-area">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="footer-copy-right">
                            <p>Copyright © 2018. All rights reserved. Template by <a href="https://colorlib.com/wp/templates/">Colorlib</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

portal/templates/portal/left_menu.html
    {% load static %}
    <div class="left-sidebar-pro">
        <nav id="sidebar" class="">
            <div class="sidebar-header">
                <a href="{% url "portal:home" %}"><img class="main-logo" src="{% static "img/logo/logosn.png" %}" alt="" /><br><span class="main-logo">Fine-Leap Systems</span></a>
                <strong><a href="{% url "portal:home" %}"><img src="{% static "img/logo/logosn.png" %}" alt="" /></a></strong>
            </div>
            <div class="left-custom-menu-adp-wrap comment-scrollbar">
                <nav class="sidebar-nav left-sidebar-menu-pro">
                    <ul class="metismenu" id="menu1">
                        <li>
                            <a title="Landing Page" href="{% url "campaigns:list" %}" aria-expanded="false"><span class="educate-icon educate-event icon-wrap sub-icon-mg" aria-hidden="true"></span> <span class="mini-click-non">Campaigns</span></a>
                        </li>

                        <li>
                            <a title="Landing Page" href="events.html" aria-expanded="false"><span class="educate-icon educate-event icon-wrap sub-icon-mg" aria-hidden="true"></span> <span class="mini-click-non">Leads</span></a>
                        </li>
                        <li>
                            <a title="Landing Page" href="events.html" aria-expanded="false"><span class="educate-icon educate-event icon-wrap sub-icon-mg" aria-hidden="true"></span> <span class="mini-click-non">Views</span></a>
                        </li>
                        <li>
                            <a title="Landing Page" href="events.html" aria-expanded="false"><span class="educate-icon educate-event icon-wrap sub-icon-mg" aria-hidden="true"></span> <span class="mini-click-non">DNCS</span></a>
                        </li>
                        <li>
                            <a title="Landing Page" href="events.html" aria-expanded="false"><span class="educate-icon educate-event icon-wrap sub-icon-mg" aria-hidden="true"></span> <span class="mini-click-non">Progress</span></a>
                        </li>
                        <li>
                            <a title="Landing Page" href="events.html" aria-expanded="false"><span class="educate-icon educate-professor icon-wrap sub-icon-mg" aria-hidden="true"></span> <span class="mini-click-non">Profile</span></a>
                        </li>

                    </ul>
                </nav>
            </div>
        </nav>
    </div>

portal/templates/portal/login.html
{% load crispy_forms_tags %}
{% load static %}
<!doctype html>
<html class="no-js" lang="en">

<head>

    {% block full_title %}
        <title>{% block title %}Login{% endblock %} | Fine-Leap Systems</title>
    {% endblock %}

    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- favicon
		============================================ -->



    <link rel="shortcut icon" type="image/x-icon" href="{% static "img/logo/favicon.png" %}">
    <!-- Google Fonts
		============================================ -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,900" rel="stylesheet">
    <!-- Bootstrap CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <!-- Bootstrap CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}">
    <!-- owl.carousel CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/owl.carousel.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.theme.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.transitions.css" %}">
    <!-- animate CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/animate.css" %}">
    <!-- normalize CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/normalize.css" %}">
    <!-- meanmenu icon CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/meanmenu.min.css" %}">
    <!-- main CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/main.css" %}">
    <!-- educate icon CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/educate-custon-icon.css" %}">
    <!-- morrisjs CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/morrisjs/morris.css" %}">
    <!-- mCustomScrollbar CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/scrollbar/jquery.mCustomScrollbar.min.css" %}">
    <!-- metisMenu CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/metisMenu/metisMenu.min.css" %}">
    <link rel="stylesheet" href="{% static "css/metisMenu/metisMenu-vertical.css" %}">
    <!-- calendar CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/calendar/fullcalendar.min.css" %}">
    <link rel="stylesheet" href="{% static "css/calendar/fullcalendar.print.min.css" %}">
    <!-- style CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <!-- responsive CSS
		============================================ -->
    <link rel="stylesheet" href="{% static "css/responsive.css" %}">
    <!-- modernizr JS
		============================================ -->
    <script src="{% static "js/vendor/modernizr-2.8.3.min.js" %}"></script>



</head>

<body>


	<div class="error-pagewrap">
		<div class="error-page-int">
			<div class="text-center m-b-md custom-login">
				<h3>PLEASE LOGIN TO FLS-CRM</h3>
			</div>
			<div class="content-error">
				<div class="hpanel">
                    <div class="panel-body">
                        <form action="#" id="loginForm" method="post">
                            {% csrf_token %}
                            {{ form|crispy }}
{#                            <div class="form-group">#}
{#                                <label class="control-label" for="username">Username</label>#}
{#                                <input type="text" placeholder="example@gmail.com" title="Please enter you username" required="" value="" name="username" id="username" class="form-control">#}
{#                                <span class="help-block small">Your unique username to app</span>#}
{#                            </div>#}
{#                            <div class="form-group">#}
{#                                <label class="control-label" for="password">Password</label>#}
{#                                <input type="password" title="Please enter your password" placeholder="******" required="" value="" name="password" id="password" class="form-control">#}
{#                                <span class="help-block small">Yur strong password</span>#}
{#                            </div>#}
                            <button type="submit" class="btn btn-success btn-block loginbtn">Login</button>
                        </form>
                    </div>
                </div>
			</div>
			<div class="text-center login-footer">
				<p>Copyright © 2018. All rights reserved. Template by <a href="https://colorlib.com/wp/templates/">Colorlib</a></p>
			</div>
		</div>
    </div>

    <script src="{% static "js/vendor/jquery-1.12.4.min.js" %}"></script>
    <!-- bootstrap JS
		============================================ -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <!-- wow JS
		============================================ -->
    <script src="{% static "js/wow.min.js" %}"></script>
    <!-- price-slider JS
		============================================ -->
    <script src="{% static "js/jquery-price-slider.js" %}"></script>
    <!-- meanmenu JS
		============================================ -->
    <script src="{% static "js/jquery.meanmenu.js" %}"></script>
    <!-- owl.carousel JS
		============================================ -->
    <script src="{% static "js/owl.carousel.min.js" %}"></script>
    <!-- sticky JS
		============================================ -->
    <script src="{% static "js/jquery.sticky.js" %}"></script>
    <!-- scrollUp JS
		============================================ -->
    <script src="{% static "js/jquery.scrollUp.min.js" %}"></script>
    <!-- counterup JS
		============================================ -->
    <script src="{% static "js/counterup/jquery.counterup.min.js" %}"></script>
    <script src="{% static "js/counterup/waypoints.min.js" %}"></script>
    <script src="{% static "js/counterup/counterup-active.js" %}"></script>
    <!-- mCustomScrollbar JS
		============================================ -->
    <script src="{% static "js/scrollbar/jquery.mCustomScrollbar.concat.min.js" %}"></script>
    <script src="{% static "js/scrollbar/mCustomScrollbar-active.js" %}"></script>
    <!-- metisMenu JS
		============================================ -->
    <script src="{% static "js/metisMenu/metisMenu.min.js" %}"></script>
    <script src="{% static "js/metisMenu/metisMenu-active.js" %}"></script>
    <!-- morrisjs JS
		============================================ -->
    <script src="{% static "js/morrisjs/raphael-min.js" %}"></script>
    <script src="{% static "js/morrisjs/morris.js" %}"></script>
    <script src="{% static "js/morrisjs/morris-active.js" %}"></script>
    <!-- morrisjs JS
		============================================ -->
    <script src="{% static "js/sparkline/jquery.sparkline.min.js" %}"></script>
    <script src="{% static "js/sparkline/jquery.charts-sparkline.js" %}"></script>
    <script src="{% static "js/sparkline/sparkline-active.js" %}"></script>
    <!-- calendar JS
		============================================ -->
    <script src="{% static "js/calendar/moment.min.js" %}"></script>
    <script src="{% static "js/calendar/fullcalendar.min.js" %}"></script>
    <script src="{% static "js/calendar/fullcalendar-active.js" %}"></script>
    <!-- plugins JS
		============================================ -->
    <script src="{% static "js/plugins.js" %}"></script>
    <!-- main JS
		============================================ -->
    <script src="{% static "js/main.js" %}"></script>
    <!-- tawk chat JS
		============================================ -->
    <script src="{% static "js/tawk-chat.js" %}"></script>

    <!-- End Scripts -->


</body>

</html>

portal/templates/portal/temp.html
{% extends "portal/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
    <br><br>

    <div class="container text-center">
        <h3>Profile | {{ executive.get_display_text }}</h3>

        <hr>

        <p>Employee id : {{ executive.get_employee_id }}</p>

        <table class="table">
            <tr>
                <td>Full Name</td>
                <td>{{ executive.get_full_name }}</td>
            </tr>
        </table>

    </div>
{% endblock %}