campaigns/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView, logout_then_login


app_name = "campaigns"

urlpatterns = [

    url(r'^list/$', views.CampaignListView.as_view(), name='list'),
    url(r'^detail/(?P<slug>[-\w]+)/$', views.CampaignDetailView.as_view(), name="detail"),
    url(r'^prospect/get/(?P<slug>[-\w]+)/$', views.prospect_get, name="prospect_get"),


    # url('(?P<slug>[-\w]+)/(?P<pk>\d+)/$', views.posts, name='posts'),

    # path('campaign/detail/<slug:slug>/', views.CampaignDetailView.as_view(), name='detail'),

]

fls_crm/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('portal.urls', namespace='portal')),
    url(r'crm_admin/', include('crm_admin.urls', namespace='crm_admin')),
    url(r'prospects/', include('prospects.urls', namespace='prospects')),
    url(r'campaigns/', include('campaigns.urls', namespace='campaigns')),
    url(r'results/', include('results.urls', namespace='results')),

]

portal/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView, logout_then_login

app_name = "portal"

urlpatterns = [
    url(r'^login/$', LoginView.as_view(template_name='portal/login.html'), name='login'),
    url(r'^logout/$', logout_then_login, name='logout'),
    url(r'^$', views.HomeView.as_view(), name='home'),

    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),

]

campaigns/models.py
from django.db import models
from django.db.models.signals import post_save, pre_save
from django.utils.text import slugify
from django.http import HttpResponse


class Campaign(models.Model):
    name = models.CharField(max_length=64)
    aim = models.CharField(max_length=128, blank=True)
    slug = models.SlugField(blank=True)
    is_active = models.BooleanField(default=True)
    script = models.TextField(blank=True)
    details = models.TextField(blank=True)
    start_date = models.DateField(blank=True)
    end_date = models.DateField(blank=True)
    executives = models.ManyToManyField('portal.Executive', blank=True)
    prospects = models.ManyToManyField('prospects.Prospect', blank=True, through='ProspectCampaignRelation')

    def __str__(self):
        return self.name

    @property
    def get_aim(self):
        if self.aim:
            return self.aim
        else:
            return "Aim not set."

    @property
    def get_short_form(self):
        return self.name[:15]

    @property
    def get_display_text(self):
        return self.name
    #
    # @property
    # def get_absolute_url(self):
    #

    @property
    def prospects_attempted(self):
        return self.prospects.filter(prospectcampaignrelation__attempted=True)

    @property
    def prospects_non_attempted(self):
        return self.prospects.filter(prospectcampaignrelation__attempted=False)

    @property
    def prospect_get(self):
        f_prospect = self.prospects_non_attempted.first()
        if f_prospect:
            f_prospect.prospectcampaignrelation.make_attempted()
            return f_prospect
        else:
            return False


def assign_slug(sender, instance, *args, **kwargs):
    slug_text = slugify(instance.name)
    if instance.slug != slug_text:
        instance.slug = slug_text
        instance.save()


pre_save.connect(assign_slug, sender=Campaign)


class ProspectCampaignRelation(models.Model):
    prospect = models.OneToOneField('prospects.Prospect', on_delete=models.CASCADE)
    campaign = models.ForeignKey(Campaign, on_delete=models.CASCADE)
    from_date = models.DateField(auto_now_add=True)
    attempted = models.BooleanField(default=False)
    details = models.TextField(blank=True)

    def __str__(self):
        return "{} -- {}".format(self.prospect, self.campaign)

    def make_attempted(self):
        # pcr = self.prospectcampaignrelation_set.get(campaign_id=campaign_id)
        # pcr = self.prospectcampaignrelation
        self.attempted = True
        self.save()
        """ Remember to use .filter with update method if this got slow"""

    class Meta:
        unique_together = ('prospect', 'campaign')

campaigns/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DeleteView, UpdateView, FormView, DetailView
from .models import Campaign, ProspectCampaignRelation
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404


class CampaignListView(LoginRequiredMixin, ListView):

    model = Campaign
    template_name = "campaigns/list.html"
    context_object_name = "campaigns"

    def get_queryset(self):
        return super().get_queryset().filter(executives__in=(self.request.user.executive, ), is_active=True)


class CampaignDetailView(LoginRequiredMixin, DetailView):

    model = Campaign
    template_name = "campaigns/detail.html"
    context_object_name = "campaign"

    def get_object(self, queryset=None):
        campaign = super().get_object()
        if self.request.user.executive  in campaign.executives.all():
            return campaign
        else:
            raise Http404("No Campaign Found")


def prospect_get(request, slug):
    campaign = get_object_or_404(Campaign, slug=slug, executives__in=(request.user.executive, ))
    prospect = campaign.prospect_get
    context = {'prospect': prospect, 'campaign': campaign}
    return render(request, 'campaigns/prospect_get.html', context)

campaigns/templates/campaigns/assign_campaign.html
{% extends "admin/base_site.html" %}

{% block content %}
    <form action="" method="post">
      {% csrf_token %}
        <p>
        Are you sure you want to assign following prospects to campaign?
        </p>
      {% for prospect in prospects %}
        <p>
          {{ prospect }}
        </p>
        <input type="hidden" name="_selected_action" value="{{ prospect.pk }}" />
      {% endfor %}

      <input type="hidden" name="action" value="assign_campaign" />
        <h4>Please select a Campaign from Dropdown </h4>

        <select name="campaign_id">
            {% for campaign in campaigns %}
                        <option value={{ campaign.id }}>{{ campaign.name }}</option>
            {% endfor %}
        </select>
      <input type="submit" name="assign" value="Assign"/>
    </form>
{% endblock %}

campaigns/templates/campaigns/detail.html
{% extends "portal/base.html" %}
{% load static %}

{% block title %}Campaigns{% endblock %}

{% block content %}


    <div class="single-pro-review-area mt-t-30 mg-b-15">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                        <div class="profile-info-inner">
                            <div class="profile-img">
                                <img src="{% static "img/crm/campaign.jpg"%}" alt="" />
                            </div>
                            <h3 class="mg-t-15">{{ campaign.get_display_text }}</h3>
                            <div class="course-des">
                                <h5 class="mg-t-15">Leads: 6 Months</h5>
                                <h5 class="mg-t-15">Views: Jane Doe</h5>
                                <h5 class="mg-t-15">DNC: 100+</h5>
                            </div>

                            <a href="{% url "campaigns:prospect_get" slug=campaign.slug %}"><button class="btn btn-primary btn-block">Get Prospect</button></a>
                        </div>
                    </div>
                    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                        <div class="product-payment-inner-st res-mg-t-30 analysis-progrebar-ctn">
                            <ul id="myTabedu1" class="tab-review-design">
                                <li class="active"><a href="#description">Activity</a></li>
                            </ul>
                            <div id="myTabContent" class="tab-content custom-product-edit">
                                <div class="product-tab-list tab-pane fade active in" id="description">
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="review-content-section">
                                                <div class="chat-discussion" style="height: auto">
                                                    <div class="chat-message">
														<div class="profile-hdtc">
															 <img class="message-avatar" src="img/contact/1.jpg" alt="">
														</div>
                                                        <div class="message">
                                                            <a class="message-author" href="#"> Michael Smith </a>
                                                            <span class="message-date"> Mon Jan 26 2015 - 18:39:23 </span>
                                                            <span class="message-content">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
															</span>
                                                            <div class="m-t-md mg-t-10">
                                                                <a class="btn btn-xs btn-default"><i class="fa fa-thumbs-up"></i> Like </a>
                                                                <a class="btn btn-xs btn-success"><i class="fa fa-heart"></i> Love</a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="chat-message">
														<div class="profile-hdtc">
															 <img class="message-avatar" src="img/contact/2.jpg" alt="">
														</div>
                                                        <div class="message">
                                                            <a class="message-author" href="#"> Karl Jordan </a>
                                                            <span class="message-date">  Fri Jan 25 2015 - 11:12:36 </span>
                                                            <span class="message-content">
																	Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover.
																	</span>
                                                            <div class="m-t-md mg-t-10">
                                                                <a class="btn btn-xs btn-default"><i class="fa fa-thumbs-up"></i> Like </a>
                                                                <a class="btn btn-xs btn-default"><i class="fa fa-heart"></i> Love</a>
                                                                <a class="btn btn-xs btn-primary"><i class="fa fa-pencil"></i> Message</a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="chat-message">
														<div class="profile-hdtc">
															 <img class="message-avatar" src="img/contact/3.jpg" alt="">
														</div>
                                                        <div class="message">
                                                            <a class="message-author" href="#"> Michael Smith </a>
                                                            <span class="message-date">  Fri Jan 25 2015 - 11:12:36 </span>
                                                            <span class="message-content">
																	There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration.
																	</span>
                                                        </div>
                                                    </div>
                                                    <div class="chat-message">
														<div class="profile-hdtc">
															 <img class="message-avatar" src="img/contact/4.jpg" alt="">
														</div>
                                                        <div class="message">
                                                            <a class="message-author" href="#"> Alice Jordan </a>
                                                            <span class="message-date">  Fri Jan 25 2015 - 11:12:36 </span>
                                                            <span class="message-content">
																	All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.
																		It uses a dictionary of over 200 Latin words.
																	</span>
                                                            <div class="m-t-md mg-t-10">
                                                                <a class="btn btn-xs btn-default"><i class="fa fa-thumbs-up"></i> Like </a>
                                                                <a class="btn btn-xs btn-warning"><i class="fa fa-eye"></i> Nudge</a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="chat-message">
														<div class="profile-hdtc">
															 <img class="message-avatar" src="img/contact/1.jpg" alt="">
														</div>
                                                        <div class="message">
                                                            <a class="message-author" href="#"> Mark Smith </a>
                                                            <span class="message-date">  Fri Jan 25 2015 - 11:12:36 </span>
                                                            <span class="message-content">
																	All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.
																		It uses a dictionary of over 200 Latin words.
																	</span>
                                                            <div class="m-t-md mg-t-10">
                                                                <a class="btn btn-xs btn-default"><i class="fa fa-thumbs-up"></i> Like </a>
                                                                <a class="btn btn-xs btn-success"><i class="fa fa-heart"></i> Love</a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="chat-message">
														<div class="profile-hdtc">
															 <img class="message-avatar" src="img/contact/2.jpg" alt="">
														</div>
                                                        <div class="message">
                                                            <a class="message-author" href="#"> Karl Jordan </a>
                                                            <span class="message-date">  Fri Jan 25 2015 - 11:12:36 </span>
                                                            <span class="message-content">
																	Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover.
																	</span>
                                                            <div class="m-t-md mg-t-10">
                                                                <a class="btn btn-xs btn-default"><i class="fa fa-thumbs-up"></i> Like </a>
                                                                <a class="btn btn-xs btn-default"><i class="fa fa-heart"></i> Love</a>
                                                                <a class="btn btn-xs btn-primary"><i class="fa fa-pencil"></i> Message</a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="chat-message">
														<div class="profile-hdtc">
															 <img class="message-avatar" src="img/contact/3.jpg" alt="">
														</div>
                                                        <div class="message">
                                                            <a class="message-author" href="#"> Michael Smith </a>
                                                            <span class="message-date">  Fri Jan 25 2015 - 11:12:36 </span>
                                                            <span class="message-content">
																	There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration.
																	</span>
                                                        </div>
                                                    </div>
                                                    <div class="chat-message">
														<div class="profile-hdtc">
															 <img class="message-avatar" src="img/contact/4.jpg" alt="">
														</div>
                                                        <div class="message">
                                                            <a class="message-author" href="#"> Alice Jordan </a>
                                                            <span class="message-date">  Fri Jan 25 2015 - 11:12:36 </span>
                                                            <span class="message-content">
																	All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.
																		It uses a dictionary of over 200 Latin words.
																	</span>
                                                            <div class="m-t-md mg-t-10">
                                                                <a class="btn btn-xs btn-default"><i class="fa fa-thumbs-up"></i> Like </a>
                                                                <a class="btn btn-xs btn-default"><i class="fa fa-heart"></i> Love</a>
                                                            </div>
                                                        </div>
                                                    </div>

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

{% endblock %}

campaigns/templates/campaigns/list.html
{% extends "portal/base.html" %}
{% load static %}
{% block title %}Campaigns{% endblock %}

{% block content %}


    <div class="contacts-area mg-b-15">
            <div class="container-fluid">
                {%  if campaigns %}
                    <div class="row">
                        {% for campaign in campaigns %}
                            <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
                                <div class="bg-primary panel-heading text-center">
                                    <h3 style="color: white!important;">{{ campaign.get_short_form }}</h3>
                                </div>
                                <div class="hpanel hblue contact-panel contact-panel-cs responsive-mg-b-30">
                                    <div class="panel-body custom-panel-jw">
                                        <p class="all-pro-ad">Campaign other name/slogun etc</p>
                                        <p>{{ campaign.details }}</p>
                                    </div>
                                    <div class="course-des">
                                        <p><span><i class="fa fa-clock"></i></span> <b>Leads:</b> 6 Months</p>
                                        <p><span><i class="fa fa-clock"></i></span> <b>Views:</b> Jane Doe</p>
                                        <p><span><i class="fa fa-clock"></i></span> <b>DNC:</b> 100+</p>
                                    </div>
                                        <a href="{% url "campaigns:detail" slug=campaign.slug %}"><button class="btn btn-primary waves-effect waves-light btn-block">Goto Camapign</button> </a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                        <span class="alert alert-warning " >No Campaigns</span>
                {% endif %}
            </div>
        </div>

{% endblock %}